### ISSUE TITLE
tokio 1.17.0 will not compile on debian stable (bullseye)

### ISSUE THREAD

**Issue by beckerj** [tokio-rs/tokio#4585]
**Version**
tokio v1.17.0

**Platform**
Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
**Description**
tokio 1.17.0 will not compile anymore on debian:
error[E0658]: use of unstable library feature 'renamed_spin_loop'

due to 
https://github.com/tokio-rs/tokio/pull/4491
because rustc minimum was elevated to 1.49.0 in
https://github.com/tokio-rs/tokio/pull/4457

debian comes with 1.48.0+dfsg1-2

I understand that you might not want to fix this because of policies, but it would be nice if you would still support debian stable.

**Comment by Darksonn** [comment]
We have several dependencies that have increased their MSRV to 1.49.0. One of them is parking_lot. I also remember that mio has upgraded, but I can't actually find their MSRV listed anywhere.

**Comment by asypost** [comment]
Maybe install the latest Rust with Rustup can fix this.

**Comment by Darksonn** [comment]
@asypost It's a legitimate concern that we don't support the rustc on debain stable, but since we have so many dependencies that require 1.49.0, it would probably take a fair amount of work to get all of them to compile on 1.48.0.

**Comment by Kixunil** [comment]
@asypost there are serious security concerns with that. Rustup doesn't perform signature verification so if their servers or certificates get compromised people are going to install malware. This is not just some theoretical concern, stuff like this already happened, one case was even a popular distro (I think Ubuntu or Mint).

@Darksonn is it feasible to persuade the dependencies to make MSRV Debian-stable-compatible? Also maybe it could still work if people pin them?

**Comment by o01eg** [comment]
What if continue support of tokio 1.16.x for Debian stable?

**Comment by Kixunil** [comment]
I think a feature would be better, maintaining two separate branches is a huge pain. Especially since I believe currently the only breakage is related to `loom` which is only needed for development, not for building.

**Comment by Darksonn** [comment]
I'm not a maintainer of all dependencies of Tokio, so I can't say for sure what they think about it, but considering its only a single version of difference, it probably isn't impossible to persuade them. 

> Also maybe it could still work if people pin them?

In the case of `parking_lot`, there's no `0.12.x` version that supports debian stable. There may be other dependencies with the same situation.

**Comment by taiki-e** [comment]
This seems difficult considering that libs team seems to be actively attempting to drop support for older versions of rustc.
https://github.com/rust-lang/libc/pull/2845

**Comment by Darksonn** [comment]
Supporting debian stable is not currently a goal, so I will close this. If the situation changes in the future to make it feasible, then I would be happy to accept PRs for that.

**Comment by taiki-e** [comment]
@TheBlueMatt When I posted that comment, the linked PR proposed increasing the MSRV to 1.56.
