### ISSUE TITLE
[0.2.7] unresolved import `tokio_macros::main_basic

### ISSUE THREAD

**Issue by andy128k** [tokio-rs/tokio#2067]
## Platform

Linux 5.4.0-1-amd64 #1 SMP Debian 5.4.6-1 (2019-12-27) x86_64 GNU/Linux

## Description

Tokio does not compile after upgrade to 0.2.7. Cargo's output:

```
error[E0432]: unresolved import `tokio_macros::main_basic`
   --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.7/src/lib.rs:276:21
    |
276 |             pub use tokio_macros::main_basic as main;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `main_basic` in the root

error[E0432]: unresolved import `tokio_macros::test_basic`
   --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.7/src/lib.rs:277:21
    |
277 |             pub use tokio_macros::test_basic as test;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `test_basic` in the root


```

**Comment by andy128k** [comment]
It looks like docs.rs has [similar issue](https://docs.rs/crate/tokio/0.2.7/builds/211137)

**Comment by emgre** [comment]
As discussed on the Discord, `tokio-macros` needs a version bump and be published on crates.io.

**Comment by vorot93** [comment]
#2068
