### ISSUE TITLE
Incorrect dependency between tokio and tokio-sync

### ISSUE THREAD

**Issue by bossmc** [tokio-rs/tokio#1056]
## Versions

tokio 0.1.19
tokio-sync 0.1.4

## Platform

`Linux 5.0.3-050003-generic #201903191333 SMP x86_64 GNU/Linux`

## Description

`tokio v0.1.19` does not compile with `tokio-sync v0.1.4`:

```
error[E0432]: unresolved import `tokio_sync::lock`
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/sync.rs:16:22
   |
16 | pub use tokio_sync::{lock, mpsc, oneshot, watch};
   |                      ^^^^ no `lock` in the root
```

This is resolved by upgrading `tokio-sync` to `v0.1.5`.  Unfortunately the `Cargo.toml` of `tokio` only depends on `tokio-sync v0.1.3` so `cargo` won't upgrade the dependency without manual intervention.

This can be worked around with `cargo update -p tokio-sync` to pull a compatible version.

Fix should be as simple as updating the dependency in `Cargo.toml` but it's worth checking if there are other similar issues rattling around.

**Comment by carllerche** [comment]
Thanks for the report. Fixed by #1054. I'll try to get crates out soon.
