### PR TITLE
uds: added solaris support in the `ucred` module

### PR DESCRIPTION
**Pull request by ohadravid**
## Motivation
When building for `x86_64-sun-solaris` (Originally to get `reqwest` to work), I got a build error about `get_peer_cred` not being implemented.

The full error message:
```
[root@localhost hello]# cross build --target x86_64-sun-solaris
   Compiling hello v0.1.0 (/project)
   Compiling tokio-uds v0.2.3
error[E0425]: cannot find function `get_peer_cred` in module `ucred`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-uds-0.2.3/src/stream.rs:116:16
    |
116 |         ucred::get_peer_cred(self)
    |                ^^^^^^^^^^^^^ not found in `ucred`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
```

## Solution

I implemented the needed function for the solaris target. It is partially based on https://github.com/LuaDist/libbsd/blob/master/src/getpeereid.c#L103, and by looking at the Oracel man pages (https://docs.oracle.com/cd/E36784_01/html/E36874/getpeerucred-3c.html).
The nessery functions are not exposed by the `libc` crate, so I added them here.

I also built a binary with the `tests` code, and confirmed that it works on a Solaris 11.4 (Since you probably don't run your tests on that).

### CODE REVIEW

**Comment by tobz** [comment]
@ohadravid Thanks for this PR!  Sorry for the long delay on responding.

I think this looks good, but you're right, we don't test on Solaris.  I'm going to see what @carllerche thinks about this, as even with small changes, not having the ability to test them ourselves might mean some users become unintentional second-class citizens if things are silently broken.

**Comment by ohadravid** [comment]
Thanks @tobz . Anything new?

**Comment by tobz** [comment]
@ohadravid I think we can merge this in.  Can you pull in `master`, though, to get the tests passing cleanly?

**Comment by ohadravid** [comment]
Done! 😄
